import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import Header from "../components/Header.js";

const DynamicPoster = dynamic(() => import("./posterSlide"));
const DynamicAward = dynamic(() => import("./awardSlide"));
const DynamicFooter = dynamic(() => import("./contactFooter"));
const DynamicPortfolio = dynamic(() => import("./portfolioSlide"));

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="poster">
        <Header />
      </div>
      <DynamicPoster />

      <div className={styles.continuePage} id="expertise">
      <div className={styles.backgroundPicture}>
          <div className={styles.backgroundMesh}>
            <DynamicPortfolio/>
          </div>
        </div>
      </div>
      <div id="award">
        <DynamicAward />
      </div>

      <footer id="contact">
        <DynamicFooter />
      </footer>
    </div>
  );
}
